version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: saminfante
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "13:49"
    timezone: US/Central
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.checkerframework:checker-qual
    versions:
    - 3.10.0
    - 3.11.0
    - 3.9.1
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: com.google.errorprone:error_prone_annotations
    versions:
    - 2.5.1
  - dependency-name: org.apache.felix:maven-bundle-plugin
    versions:
    - 5.1.1
  - dependency-name: org.codehaus.mojo:animal-sniffer-annotations
    versions:
    - "1.19"
  - dependency-name: org.codehaus.mojo:animal-sniffer-maven-plugin
    versions:
    - "1.19"
  - dependency-name: org.easymock:easymock
    versions:
    - "4.2"
  registries:
  - git-github-com
